# Generated by Django 4.0.6 on 2022-07-31 19:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_alter_wishlist_product_alter_wishlist_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='WishItem',
        ),
    ]
