# Generated by Django 4.0.6 on 2022-08-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
